/**
 * This file was generated by kysely-codegen (via Floot's kysely-postgres-js integration).
 * Please do not edit it manually — regenerate from database/001_multi_tenant_foundation.sql.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type InventoryMovementType = "adjustment" | "reservation_release" | "restock" | "return" | "sale";

export type Json = JsonValue;
export type JsonArray = JsonValue[];
export type JsonObject = { [x: string]: JsonValue | undefined };
export type JsonPrimitive = boolean | number | string | null;
export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type ProductStatus = "active" | "archived" | "draft";
export type TenantRole = "admin" | "inventory" | "manager" | "owner" | "sales" | "support";
export type TenantStatus = "active" | "deleted" | "suspended" | "trial";
export type Timestamp = ColumnType<Date, Date | string, Date | string>;
export type UserRole = "admin" | "super_admin" | "user";

export interface AuditLogs {
  action: string;
  actorUserId: number | null;
  createdAt: Generated<Timestamp>;
  entityId: number | null;
  entityType: string;
  id: Generated<number>;
  metadata: Generated<Json>;
  tenantId: number | null;
}

export interface Brands {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  slug: string;
  tenantId: number;
}

export interface Categories {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  imageUrl: string | null;
  name: string;
  parentId: number | null;
  position: Generated<number>;
  slug: string;
  tenantId: number;
}

export interface InventoryMovements {
  createdAt: Generated<Timestamp>;
  createdByUserId: number | null;
  id: Generated<number>;
  productId: number;
  quantityChange: number;
  reason: string | null;
  referenceId: number | null;
  referenceType: string | null;
  tenantId: number;
  type: InventoryMovementType;
  variantId: number | null;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface ProductImages {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  position: Generated<number>;
  productId: number;
  url: string;
}

export interface Products {
  brandId: number | null;
  categoryId: number | null;
  cost: Numeric | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  dimensionsCm: Generated<Json>;
  hasVariants: Generated<boolean>;
  id: Generated<number>;
  lowStockThreshold: Generated<number>;
  name: string;
  price: Numeric;
  salePrice: Numeric | null;
  sku: string | null;
  slug: string;
  status: Generated<ProductStatus>;
  stockQuantity: Generated<number>;
  taxRate: Generated<Numeric>;
  tenantId: number;
  updatedAt: Generated<Timestamp>;
  videoUrl: string | null;
  weightKg: Numeric | null;
}

export interface ProductVariants {
  attributes: Generated<Json>;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  imageUrl: string | null;
  price: Numeric;
  productId: number;
  salePrice: Numeric | null;
  sku: string | null;
  stockQuantity: Generated<number>;
  tenantId: number;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface Stores {
  contactEmail: string | null;
  contactPhone: string | null;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  currencySymbol: Generated<string>;
  customDomain: string | null;
  customDomainVerified: Generated<boolean>;
  faviconUrl: string | null;
  id: Generated<number>;
  isPublished: Generated<boolean>;
  logoUrl: string | null;
  onboardingCompletedAt: Timestamp | null;
  onboardingStep: Generated<string>;
  primaryColor: string | null;
  socialLinks: Generated<Json>;
  storeName: string;
  subdomain: string;
  tenantId: number;
  theme: Generated<string>;
  timezone: Generated<string>;
  updatedAt: Generated<Timestamp>;
  whatsappNumber: string | null;
}

export interface Tenants {
  createdAt: Generated<Timestamp>;
  createdByUserId: number;
  id: Generated<number>;
  name: string;
  slug: string;
  status: Generated<TenantStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface TenantUsers {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  invitedAt: Generated<Timestamp>;
  invitedByUserId: number | null;
  joinedAt: Timestamp | null;
  role: TenantRole;
  tenantId: number;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export type OrderStatus = "pending" | "paid" | "processing" | "shipped" | "delivered" | "cancelled";
export type PaymentStatus = "unpaid" | "paid" | "failed" | "refunded";
export type PaymentProvider = "paystack" | "hubtel";
export type PaymentTransactionStatus = "pending" | "success" | "failed";

export interface DeliveryZones {
  id: Generated<number>;
  tenantId: number;
  name: string;
  fee: Numeric;
  freeDeliveryThreshold: Numeric | null;
  estimatedDaysMin: Generated<number>;
  estimatedDaysMax: Generated<number>;
  isActive: Generated<boolean>;
  createdAt: Generated<Timestamp | null>;
}

export interface Customers {
  id: Generated<number>;
  tenantId: number;
  email: string;
  phone: string | null;
  name: string;
  passwordHash: string | null;
  createdAt: Generated<Timestamp | null>;
}

export interface CustomerAddresses {
  id: Generated<number>;
  customerId: number;
  label: string | null;
  recipientName: string;
  phone: string;
  addressLine: string;
  city: string;
  region: string | null;
  isDefault: Generated<boolean>;
  createdAt: Generated<Timestamp | null>;
}

export interface Orders {
  id: Generated<number>;
  tenantId: number;
  orderNumber: string;
  customerId: number | null;
  guestEmail: string | null;
  recipientName: string;
  recipientPhone: string;
  deliveryAddress: string;
  deliveryCity: string;
  deliveryZoneId: number | null;
  deliveryFee: Numeric;
  subtotal: Numeric;
  total: Numeric;
  currency: Generated<string>;
  status: Generated<OrderStatus>;
  paymentStatus: Generated<PaymentStatus>;
  notes: string | null;
  createdAt: Generated<Timestamp | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface OrderItems {
  id: Generated<number>;
  orderId: number;
  productId: number | null;
  variantId: number | null;
  nameSnapshot: string;
  skuSnapshot: string | null;
  unitPrice: Numeric;
  quantity: number;
  subtotal: Numeric;
}

export interface OrderStatusHistory {
  id: Generated<number>;
  orderId: number;
  status: OrderStatus;
  note: string | null;
  createdByUserId: number | null;
  createdAt: Generated<Timestamp | null>;
}

export interface PaymentCredentials {
  id: Generated<number>;
  tenantId: number;
  provider: PaymentProvider;
  publicKey: string | null;
  secretKeyEncrypted: string;
  isActive: Generated<boolean>;
  createdAt: Generated<Timestamp | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface PaymentTransactions {
  id: Generated<number>;
  tenantId: number;
  orderId: number;
  provider: PaymentProvider;
  reference: string;
  amount: Numeric;
  currency: Generated<string>;
  status: Generated<PaymentTransactionStatus>;
  channel: string | null;
  providerTransactionId: string | null;
  rawWebhookPayload: Json | null;
  createdAt: Generated<Timestamp | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface SubscriptionPlans {
  id: Generated<number>;
  name: string;
  slug: string;
  description: string | null;
  priceMonthly: number;
  priceYearly: number;
  currency: string;
  maxProducts: number;
  maxStaff: number;
  maxStorageGb: number;
  hasCustomDomain: boolean;
  hasAdvancedAnalytics: boolean;
  hasCouponSystem: boolean;
  hasEmailSupport: boolean;
  hasPrioritySupport: boolean;
  hasApiAccess: boolean;
  commissionRate: number;
  isActive: boolean;
  isPopular: boolean;
  sortOrder: number;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface MerchantSubscriptions {
  id: Generated<number>;
  tenantId: number;
  planId: number;
  status: string;
  billingCycle: string;
  startedAt: Generated<Timestamp>;
  currentPeriodStart: Generated<Timestamp>;
  currentPeriodEnd: Timestamp;
  trialEndsAt: Timestamp | null;
  cancelledAt: Timestamp | null;
  amount: number | null;
  currency: string;
  stripeSubscriptionId: string | null;
  cancelReason: string | null;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface SubscriptionUsage {
  id: Generated<number>;
  subscriptionId: number;
  productsCount: number;
  staffCount: number;
  storageUsedMb: number;
  ordersCount: number;
  periodStart: Generated<Timestamp>;
  periodEnd: Timestamp;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface SubscriptionInvoices {
  id: Generated<number>;
  tenantId: number;
  subscriptionId: number | null;
  planId: number | null;
  invoiceNumber: string;
  amount: number;
  taxAmount: number;
  totalAmount: number;
  currency: string;
  periodStart: Timestamp;
  periodEnd: Timestamp;
  status: string;
  paymentMethod: string | null;
  paidAt: Timestamp | null;
  stripeInvoiceId: string | null;
  stripePaymentIntentId: string | null;
  pdfUrl: string | null;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface PlanFeatures {
  id: Generated<number>;
  planId: number;
  featureKey: string;
  featureValue: string;
  createdAt: Generated<Timestamp>;
}

export interface DB {
  auditLogs: AuditLogs;
  brands: Brands;
  categories: Categories;
  customerAddresses: CustomerAddresses;
  customers: Customers;
  deliveryZones: DeliveryZones;
  inventoryMovements: InventoryMovements;
  loginAttempts: LoginAttempts;
  merchantSubscriptions: MerchantSubscriptions;
  orderItems: OrderItems;
  orders: Orders;
  orderStatusHistory: OrderStatusHistory;
  paymentCredentials: PaymentCredentials;
  paymentTransactions: PaymentTransactions;
  planFeatures: PlanFeatures;
  productImages: ProductImages;
  products: Products;
  productVariants: ProductVariants;
  sessions: Sessions;
  stores: Stores;
  subscriptionInvoices: SubscriptionInvoices;
  subscriptionPlans: SubscriptionPlans;
  subscriptionUsage: SubscriptionUsage;
  tenants: Tenants;
  tenantUsers: TenantUsers;
  userPasswords: UserPasswords;
  users: Users;
}

export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin", "super_admin", "user"];
export const TenantStatusArrayValues: [TenantStatus, ...TenantStatus[]] = ["active", "deleted", "suspended", "trial"];
export const TenantRoleArrayValues: [TenantRole, ...TenantRole[]] = ["admin", "inventory", "manager", "owner", "sales", "support"];
export const ProductStatusArrayValues: [ProductStatus, ...ProductStatus[]] = ["active", "archived", "draft"];
export const InventoryMovementTypeArrayValues: [InventoryMovementType, ...InventoryMovementType[]] = ["adjustment", "reservation_release", "restock", "return", "sale"];

